spring:
  application:
    name: demo
  datasource:
    url: "jdbc:mysql://localhost:3306/monitor"
    username: root
    password: jaheernazia
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate.naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"

my.message :  Hello World

management.endpoints.web.exposure.include: "*"